services:
  postgres:
    container_name: msd_pg_sql
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lucy
      POSTGRES_PASSWORD: lucy
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net

  pgadmin:
    container_name: msd_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net

  mongodb:
    container_name: msd_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lucy
      - MONGO_INITDB_ROOT_PASSWORD=lucy
    networks:
      - microservices-net

  mongo-express:
    container_name: msd_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=lucy
      - ME_CONFIG_MONGODB_ADMINPASSWORD=lucy
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - microservices-net

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.3
    command: start-dev
    restart: unless-stopped
    ports:
      - 9082:8080
    environment:
      KEYCLOAK_ADMIN: lucy
      KEYCLOAK_ADMIN_PASSWORD: lucy
#      KC_DB: postgres
#      KC_DB_SCHEMA: public
#      KC_DB_USERNAME: ${DB_USER:-lucy}
#      KC_DB_PASSWORD: ${DB_PASS:-lucy}
#      KC_DB_URL: ${DB_URL:-jdbc:postgresql://postgres:5432/keycloak}
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    volumes:
      - keycloak:/opt/keycloak/data
    networks:
      - microservices-net
    links:
      - postgres


  mail-dev:
    container_name: msd_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
  keycloak:
