spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service
app:
  keycloak:
    admin:
      clientId:
      clientSecret:
    realm: chitrastra
    serverUrl: http://localhost:9082