spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9082/realms/my-app-realm # Resource server uses 'my-app-realm'

app:
  keycloak:
    admin:
      clientId:
      clientSecret:
    realm: chitrastra # Note: Keycloak Admin client targets 'chitrastra'
    serverUrl: http://localhost:9082

server:
  port: 8080 # Default port for users-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true